#!/bin/bash

export LD_LIBRARY_PATH="`dirname "$0"`/../lib/"
# Workaround for macosx gatekeeper, starting from v10.10.4
chmod +x "`dirname "$0"`/avrdude_bin"
exec -a "$0" "`dirname "$0"`/avrdude_bin" "$@"
